### ISSUE TITLE
Boltz2 compatibility with Blackwell GPU

### ISSUE THREAD

**Issue by CLG68** [jwohlwend/boltz#484]
Hi,

I'm running Boltz2 on a Ada Lovelace GPU without problem, apart from having Ca2+being declared as a Carbon in created complexes...  Still Boltz2 is running.

On a PC with a Blackwell GPU RTX 5070 Ti 16Gb, "Boltz2 fails with a CalledProcessError: Compile with 'TORCH_USE_CUDA_DSA' to enable device-side assertions' error.  

Setting the export TORCH_USE_CUDA_DSA=1 environment variable does not change the error message.

Best

**Comment by CLG68** [comment]
I solved the problem, I'll leave it opened so you could maybe update your Readme file for those using Blackwell GPU.

I needed to preinstall the nightly built Pytorch version:

conda create -n boltz2 python=3.12 -y
conda activate boltz2

pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cu128

pip install boltz[cuda] -U

In fact, it did not work the first time I installed boltz as it was giving me:

from boltz.main import cli
ModuleNotFoundError: No module named 'boltz'

so I uninstalled/reinstalled it and now it works.

**Comment by CLG68** [comment]
Thank you, 

I'll try 2.7.1, it could be more stable
